# Generated by Django 4.2.7 on 2024-01-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creator",
            name="country",
            field=models.CharField(default="USA", max_length=50),
            preserve_default=False,
        ),
    ]
